# generated by datamodel-codegen:
#   filename:  test.json
#   timestamp: 2023-12-04T18:04:38+00:00

from __future__ import annotations

from pydantic import BaseModel


class MessageRegenerate(BaseModel):
    status: str
    statusMessage: str


class Data(BaseModel):
    messageRegenerate: MessageRegenerate


class Extensions(BaseModel):
    is_final: bool


class RegenerateMessageResponse(BaseModel):
    data: Data
    extensions: Extensions
