# generated by datamodel-codegen:
#   filename:  test.json
#   timestamp: 2023-12-02T12:41:49+00:00

from __future__ import annotations

from pydantic import BaseModel

from ..bot import BotWithPrompt


class Viewer(BaseModel):
    decoupleBotHandleAndName: bool
    id: str
    enableBotMetadata: bool


class Data(BaseModel):
    bot: BotWithPrompt
    viewer: Viewer


class Extensions(BaseModel):
    is_final: bool


class ResponseByBotName(BaseModel):
    data: Data
    extensions: Extensions
